### ISSUE TITLE
dotify without github

### ISSUE THREAD

**Issue by chriskempson** [mdespuits/dotify#10]
I see there's a `dotify github` command but what if you don't want to use github?

**Comment by mdespuits** [comment]
Since most of the developers I know use Github for a lot of their closed and open source projects, I chose that as the default. I had plans to eventually support custom locations, but that is not currently high on the current todo list (the number one being refactoring and improving the OO design of the codebase).

If this is something that you think that you and other people would really need, I might consider bumping it up in priority, however for you you could just create a repo in Github and use it here temporarily for now.

**Comment by chriskempson** [comment]
I guess I could work something out with most of my existing repo moved over to GH. Maybe it's not a good practice but I keep my SSH keys in my private repo hence it's not suitable for a public GH repo and I don't really wish to pay for a private GH repo just for this.

I can't really say how useful this would be to other people so I decided to roll my own script to take care of my dotfile syncing needs. Will certainly keep an eye on dotify however as I like where it's heading.

**Comment by mdespuits** [comment]
See the [CHANGELOG](https://github.com/mattdbridges/dotify/blob/master/CHANGELOG.md) for upcoming work on this issue.
