### ISSUE TITLE
Meaning of [Yn]

### ISSUE THREAD

**Issue by chriskempson** [mdespuits/dotify#11]
I've just spent a couple of hours trying to figure out why when presented with the prompt `Do you want to link [file] to Dotify? [Yn]` and hitting enter, no link was made, no message was given.

Turns out you have to type `Y` and then hit enter. I'm hoping this is a bug and not the intended way it should work?

**Comment by mdespuits** [comment]
@chriskempson This is the intended way it should work. Unfortunately, I do not have control over this behavior as the user dialogue in `dotify`'s tasks are powered by `thor`. Since it requires an answer to be pass a true value to the conditional being given, hitting the `enter` key does not do this.

I have done some digging around in `thor` and it seems that this is the desired behavior. See [the `yes?` method](https://github.com/wycats/thor/blob/master/lib/thor/shell/basic.rb#L96) to get a better idea.

However, the part about no message being given is important. I had that in place in a previous version and somehow it got lost/dropped. I need to add that back in to the next version for better usability. Thanks!

**Comment by chriskempson** [comment]
Thanks very much for the explanation. Maybe the message could be changed to `[y/n]` the '/' may help indicate itls one or the other whereas a capital letter can often denote a default choice should nothing be entered.

Anyway, glad to hear there's a message coming back, that will certainly help!

**Comment by mdespuits** [comment]
That is a very good point. I had not considered that the capital might be the default option. I will be making that change in a future release.
